// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQsTLm4NWySwoHdg6E9S-o-vtZzvlU2q8',
    appId: '1:75523934173:web:bea22b55355262d1869834',
    messagingSenderId: '75523934173',
    projectId: 'sampletest-4273e',
    authDomain: 'sampletest-4273e.firebaseapp.com',
    storageBucket: 'sampletest-4273e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC_OKUUdnK4oBPHvu0V9yhayQjV7_Dop4',
    appId: '1:75523934173:android:16dc4af3a516845a869834',
    messagingSenderId: '75523934173',
    projectId: 'sampletest-4273e',
    storageBucket: 'sampletest-4273e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCybcRu3W2T8f8aC0gvd-Z6TxAWMHlVBxI',
    appId: '1:75523934173:ios:061e2978ac360e6d869834',
    messagingSenderId: '75523934173',
    projectId: 'sampletest-4273e',
    storageBucket: 'sampletest-4273e.appspot.com',
    iosClientId: '75523934173-3j4jkbk9crvj4a1m7mf2k9re76ul4i37.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample',
  );
}
