// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQsTLm4NWySwoHdg6E9S-o-vtZzvlU2q8',
    appId: '1:75523934173:web:4305ec2cbe09659f869834',
    messagingSenderId: '75523934173',
    projectId: 'sampletest-4273e',
    authDomain: 'sampletest-4273e.firebaseapp.com',
    storageBucket: 'sampletest-4273e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC_OKUUdnK4oBPHvu0V9yhayQjV7_Dop4',
    appId: '1:75523934173:android:1a05270b10f127a5869834',
    messagingSenderId: '75523934173',
    projectId: 'sampletest-4273e',
    storageBucket: 'sampletest-4273e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCybcRu3W2T8f8aC0gvd-Z6TxAWMHlVBxI',
    appId: '1:75523934173:ios:f0bf27007e97c5cc869834',
    messagingSenderId: '75523934173',
    projectId: 'sampletest-4273e',
    storageBucket: 'sampletest-4273e.appspot.com',
    androidClientId: '75523934173-4stcp4lqukhmgm4cvjkpjhefgg28vjv7.apps.googleusercontent.com',
    iosClientId: '75523934173-2m67pr6ophc8bohe1secbvaa6edg90nq.apps.googleusercontent.com',
    iosBundleId: 'br.uff.sample',
  );
}
